// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package backoff

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockBackoff is an autogenerated mock type for the Backoff type
type MockBackoff struct {
	mock.Mock
}

// Delay provides a mock function with given fields: _a0
func (_m *MockBackoff) Delay(_a0 int) time.Duration {
	ret := _m.Called(_a0)

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func(int) time.Duration); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}
